---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name.saving-goal-planner}
    username: ${spring.datasource.username.saving-goal-planner}
    password: ${spring.datasource.password.saving-goal-planner}
    url: ${spring.datasource.url.saving-goal-planner}
