---
### Live profile
spring:
  profiles: live
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    username: ${spring.datasource.username.contact-manager}
    password: ${spring.datasource.password.contact-manager}
    url: ${spring.datasource.url.contact-manager}

backbase:
  api:
    extensions: # Contact Extensions Example
      classes:
        # Presentation spec
        com.backbase.presentation.contact.rest.spec.v2.contacts.ContactsPostRequestBody: pokemon-data
        com.backbase.presentation.contact.rest.spec.v2.contacts.ContactPutRequestBody: pokemon-data
        com.backbase.presentation.contact.rest.spec.v2.contacts.AccountInformation: pokemon-data
        # Persistence spec
        com.backbase.dbs.party.persistence.spec.v2.parties.PartyDto: pokemon-data
        com.backbase.dbs.party.persistence.spec.v2.parties.AccountInformation: pokemon-data
        # Persistence entities
        com.backbase.dbs.contactmanager.party.persistence.Party: pokemon-data
        com.backbase.dbs.contactmanager.party.persistence.AccountInformation: pokemon-data
      property-sets:
        pokemon-data:
          properties:
          - property-name: favPokemon
            security:
            - confidential
            type: string
          - property-name: rank
            security:
            - confidential
            type: number
  audit:
    enabled: false
  security:
    mtls:
      enabled: false      
